"""screening verdict

Revision ID: 41f715bf8ba1
Revises: a6217052966a
Create Date: 2026-08-06 15:11:35.447647

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '41f715bf8ba1'
down_revision: Union[str, Sequence[str], None] = 'a6217052966a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('competitors', sa.Column('kind', sa.Text(), nullable=True))
    op.add_column('competitors', sa.Column('screening_note', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('competitors', 'screening_note')
    op.drop_column('competitors', 'kind')
    # ### end Alembic commands ###
