"""promotion last_seen_at

Revision ID: a6217052966a
Revises: a9aa03bafc53
Create Date: 2026-08-06 12:09:34.394404

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a6217052966a'
down_revision: Union[str, Sequence[str], None] = 'a9aa03bafc53'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # SQLite не даёт добавить NOT NULL без значения — заполняем существующие строки
    # временем первой фиксации акции, затем снимаем server_default.
    op.add_column(
        'promotions',
        sa.Column(
            'last_seen_at',
            sa.DateTime(),
            nullable=False,
            server_default='1970-01-01 00:00:00',
        ),
    )
    op.execute("UPDATE promotions SET last_seen_at = captured_at")
    with op.batch_alter_table('promotions') as batch:
        batch.alter_column('last_seen_at', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('promotions', 'last_seen_at')
    # ### end Alembic commands ###
